# Generated by Django 4.2.1 on 2023-05-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
                ('nickname', models.CharField(max_length=20, verbose_name='nickname')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('view_count', models.IntegerField(verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user', verbose_name='writer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_on', models.DateTimeField(verbose_name='created on')),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='comment on')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user', verbose_name='writer')),
            ],
        ),
    ]
